# Generated by Django 3.0.4 on 2020-03-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamodelo',
            name='descripcion',
            field=models.TextField(help_text='Descripción de la Categoría', max_length=100, unique=True),
        ),
    ]
